### ISSUE TITLE
Cash class (story problems) all art and layout

### ISSUE THREAD

**Issue by sephirob** [brycethorup/cash-class-tracker#22]
Includes all vegetables, veg in crates, etc.

**Comment by sephirob** [comment]
5&Dime CashClass.ai, fruid and veg in crate.ai, and Fruit&Veg.ai have all the assets and layout elements for this activity

**Comment by brycethorup** [comment]
@sephirob should there be more than just the tomatoes in the "fruit and veg in crate.ai" file? I'm not seeing any additional layers or assets, just the crate with tomatoes.

**Comment by sephirob** [comment]
There totally should, I will look at that and reupload it. Thanks for letting me know!

**Comment by brycethorup** [comment]
@sephirob I just got done setting up this activity so that it provides more coins automatically depending on the difficulty so that there will always be enough. I was wondering if we have a need for the "Add Coin" button here? Here are some screen grabs to give you an idea of what is going on here. Of course the amounts will be dependent on how much the most expensive item is multiplied by the max number of pounds possible.
![screenshot 2015-11-11 at 8 38 53 pm](https://cloud.githubusercontent.com/assets/5115724/11110029/71920028-88b4-11e5-99da-7277314d2012.png)
![screenshot 2015-11-11 at 8 39 04 pm](https://cloud.githubusercontent.com/assets/5115724/11110030/7192490c-88b4-11e5-8f5d-3f9bf725c7a4.png)
![screenshot 2015-11-11 at 8 39 17 pm](https://cloud.githubusercontent.com/assets/5115724/11110031/7194fbc0-88b4-11e5-876e-15f10f4f4a60.png)
![screenshot 2015-11-11 at 8 39 29 pm](https://cloud.githubusercontent.com/assets/5115724/11110032/71994e96-88b4-11e5-8227-545f4249c6c2.png)
![screenshot 2015-11-11 at 8 39 41 pm](https://cloud.githubusercontent.com/assets/5115724/11110033/719ca64a-88b4-11e5-93a8-1e403ad90d40.png)

**Comment by sephirob** [comment]
I think you're completely right and we dont need the Add Coin here. I removed it from the final layout version. Your method is much better, clearer, and works with scaling difficulty much better. =)

**Comment by sephirob** [comment]
Oh! Also I updated the +Coin button to have a ¢ on the circle so maybe its a bit more clear what the button is for. The buttons.ai is updated.
